with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/cronnoss/tk-api/internal/server:
    interfaces:
      Logger:
      Application:
